import { AppConfigProvider } from "@/context/app-config";
import "../globals.css";
import Statics from "@/statics";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const appConfig = await fetch(Statics.storeURL + "config.json", {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
    next: { revalidate: 3600 },
  }).then((res) => res.json());

  return (
    <html lang="en">
      <body>
        <AppConfigProvider data={appConfig}>{children}</AppConfigProvider>
      </body>
    </html>
  );
}
